// <auto-generated />
using System;
using Dartz.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dartz.Business.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250102115950_add-friends")]
    partial class addfriends
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dartz.Model.DBThrow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Multiplier1")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier2")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier3")
                        .HasColumnType("integer");

                    b.Property<int>("Score1")
                        .HasColumnType("integer");

                    b.Property<int>("Score2")
                        .HasColumnType("integer");

                    b.Property<int>("Score3")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Throws");
                });

            modelBuilder.Entity("Dartz.Model.GameSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("WinnerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Dartz.Model.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Dartz.Model.PlayerSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("AllowNoAuth")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("Dartz.Model.PlayerThrow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("SessionID")
                        .HasColumnType("integer");

                    b.Property<int>("ThrowID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("SessionID");

                    b.HasIndex("ThrowID");

                    b.ToTable("PlayerThrows");
                });

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.Property<int>("GameSessionsID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersID")
                        .HasColumnType("integer");

                    b.HasKey("GameSessionsID", "PlayersID");

                    b.HasIndex("PlayersID");

                    b.ToTable("GameSessionPlayer");
                });

            modelBuilder.Entity("Dartz.Model.Player", b =>
                {
                    b.HasOne("Dartz.Model.Player", null)
                        .WithMany("Friends")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("Dartz.Model.PlayerThrow", b =>
                {
                    b.HasOne("Dartz.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.GameSession", "Session")
                        .WithMany("PlayerThrows")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.DBThrow", "Throw")
                        .WithMany()
                        .HasForeignKey("ThrowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");

                    b.Navigation("Throw");
                });

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.HasOne("Dartz.Model.GameSession", null)
                        .WithMany()
                        .HasForeignKey("GameSessionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dartz.Model.GameSession", b =>
                {
                    b.Navigation("PlayerThrows");
                });

            modelBuilder.Entity("Dartz.Model.Player", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
