// <auto-generated />
using System;
using Dartz.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dartz.Business.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260223190848_MatchHistory")]
    partial class MatchHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dartz.Model.DBThrow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Multiplier1")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier2")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier3")
                        .HasColumnType("integer");

                    b.Property<int>("Score1")
                        .HasColumnType("integer");

                    b.Property<int>("Score2")
                        .HasColumnType("integer");

                    b.Property<int>("Score3")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Throws");
                });

            modelBuilder.Entity("Dartz.Model.Dart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("DartNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<int>("TurnID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TurnID");

                    b.ToTable("Darts");
                });

            modelBuilder.Entity("Dartz.Model.GameSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("WinnerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Dartz.Model.Leg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MatchID")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerPlayerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.HasIndex("WinnerPlayerID");

                    b.ToTable("Legs");
                });

            modelBuilder.Entity("Dartz.Model.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameModeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Legs")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WinnerPlayerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("WinnerPlayerID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Dartz.Model.MatchPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("FinalLegs")
                        .HasColumnType("integer");

                    b.Property<int>("FinalSets")
                        .HasColumnType("integer");

                    b.Property<int>("MatchID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerIndex")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.HasIndex("PlayerID");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Dartz.Model.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Dartz.Model.PlayerSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("AllowNoAuth")
                        .HasColumnType("boolean");

                    b.Property<string>("DartColor")
                        .HasColumnType("text");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("PlayerSettings");
                });

            modelBuilder.Entity("Dartz.Model.PlayerStats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("BestLegDarts")
                        .HasColumnType("integer");

                    b.Property<int>("Count100Plus")
                        .HasColumnType("integer");

                    b.Property<int>("Count140Plus")
                        .HasColumnType("integer");

                    b.Property<int>("Count180s")
                        .HasColumnType("integer");

                    b.Property<int>("HighestTurnScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OverallAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLegs")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLegsWon")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID")
                        .IsUnique();

                    b.ToTable("PlayerStatsSet");
                });

            modelBuilder.Entity("Dartz.Model.PlayerThrow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("PlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("SessionID")
                        .HasColumnType("integer");

                    b.Property<int>("ThrowID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("SessionID");

                    b.HasIndex("ThrowID");

                    b.ToTable("PlayerThrows");
                });

            modelBuilder.Entity("Dartz.Model.Turn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsBust")
                        .HasColumnType("boolean");

                    b.Property<int>("LegID")
                        .HasColumnType("integer");

                    b.Property<int>("MatchPlayerID")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreBefore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("LegID");

                    b.HasIndex("MatchPlayerID");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.Property<int>("GameSessionsID")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersID")
                        .HasColumnType("integer");

                    b.HasKey("GameSessionsID", "PlayersID");

                    b.HasIndex("PlayersID");

                    b.ToTable("GameSessionPlayer");
                });

            modelBuilder.Entity("PlayerFriendship", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("PlayerFriendships", (string)null);
                });

            modelBuilder.Entity("Dartz.Model.Dart", b =>
                {
                    b.HasOne("Dartz.Model.Turn", "Turn")
                        .WithMany("Darts")
                        .HasForeignKey("TurnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Dartz.Model.Leg", b =>
                {
                    b.HasOne("Dartz.Model.Match", "Match")
                        .WithMany("MatchLegs")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.Player", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("Dartz.Model.Match", b =>
                {
                    b.HasOne("Dartz.Model.Player", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("Dartz.Model.MatchPlayer", b =>
                {
                    b.HasOne("Dartz.Model.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Dartz.Model.PlayerStats", b =>
                {
                    b.HasOne("Dartz.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Dartz.Model.PlayerThrow", b =>
                {
                    b.HasOne("Dartz.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.GameSession", "Session")
                        .WithMany("PlayerThrows")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.DBThrow", "Throw")
                        .WithMany()
                        .HasForeignKey("ThrowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");

                    b.Navigation("Throw");
                });

            modelBuilder.Entity("Dartz.Model.Turn", b =>
                {
                    b.HasOne("Dartz.Model.Leg", "Leg")
                        .WithMany("Turns")
                        .HasForeignKey("LegID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.MatchPlayer", "MatchPlayer")
                        .WithMany("Turns")
                        .HasForeignKey("MatchPlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leg");

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.HasOne("Dartz.Model.GameSession", null)
                        .WithMany()
                        .HasForeignKey("GameSessionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerFriendship", b =>
                {
                    b.HasOne("Dartz.Model.Player", null)
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dartz.Model.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dartz.Model.GameSession", b =>
                {
                    b.Navigation("PlayerThrows");
                });

            modelBuilder.Entity("Dartz.Model.Leg", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Dartz.Model.Match", b =>
                {
                    b.Navigation("MatchLegs");

                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("Dartz.Model.MatchPlayer", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Dartz.Model.Turn", b =>
                {
                    b.Navigation("Darts");
                });
#pragma warning restore 612, 618
        }
    }
}
