import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/navigation";
import FriendList from "./components/friendList/friendList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-cols-12 gap-7">
        <div className='col-span-2'>
          <Navigation />
        </div>
        <div className={'col-span-8 '+inter.className}>{children}</div>        
        <div className='col-span-2'>
          <FriendList/>
       </div>
      </body>

    </html>
  );
}
